import type {
  User,
  Policy,
  DataAsset,
  AIUsageEvent,
  Alert,
  ComplianceFramework,
  DashboardMetrics,
  TimeSeriesData,
  AITool,
} from './types';

// Dashboard Metrics
export const dashboardMetrics: DashboardMetrics = {
  totalRequests: 284567,
  blockedRequests: 1243,
  activeUsers: 2847,
  policiesEnforced: 47,
  dataAssetsProtected: 12453,
  complianceScore: 94,
  riskScore: 23,
  alertsToday: 12,
};

// Users
export const users: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    department: 'Engineering',
    role: 'Senior Developer',
    riskScore: 15,
    lastActivity: new Date('2026-01-31T10:30:00'),
    aiToolsAccess: ['ChatGPT', 'GitHub Copilot', 'Claude'],
  },
  {
    id: '2',
    name: 'Michael Torres',
    email: 'michael.torres@company.com',
    department: 'Sales',
    role: 'Account Executive',
    riskScore: 42,
    lastActivity: new Date('2026-01-31T09:15:00'),
    aiToolsAccess: ['ChatGPT', 'Jasper'],
  },
  {
    id: '3',
    name: 'Emily Watson',
    email: 'emily.watson@company.com',
    department: 'Legal',
    role: 'Compliance Officer',
    riskScore: 8,
    lastActivity: new Date('2026-01-31T11:45:00'),
    aiToolsAccess: ['ChatGPT', 'Claude'],
  },
  {
    id: '4',
    name: 'James Liu',
    email: 'james.liu@company.com',
    department: 'Finance',
    role: 'Financial Analyst',
    riskScore: 67,
    lastActivity: new Date('2026-01-31T08:20:00'),
    aiToolsAccess: ['ChatGPT', 'Excel Copilot'],
  },
  {
    id: '5',
    name: 'Amanda Brooks',
    email: 'amanda.brooks@company.com',
    department: 'HR',
    role: 'HR Manager',
    riskScore: 31,
    lastActivity: new Date('2026-01-31T10:00:00'),
    aiToolsAccess: ['ChatGPT', 'Grammarly'],
  },
];

// Policies
export const policies: Policy[] = [
  {
    id: '1',
    name: 'PII Protection Policy',
    description: 'Prevents personally identifiable information from being shared with AI tools',
    status: 'active',
    dataClassifications: ['confidential', 'restricted'],
    allowedTools: ['GitHub Copilot'],
    blockedPatterns: ['SSN', 'social security', 'passport', 'credit card', 'bank account'],
    createdAt: new Date('2025-06-15'),
    updatedAt: new Date('2026-01-15'),
    enforcementLevel: 'block',
  },
  {
    id: '2',
    name: 'Financial Data Policy',
    description: 'Controls how financial data can be processed by AI systems',
    status: 'active',
    dataClassifications: ['confidential', 'restricted'],
    allowedTools: ['Excel Copilot'],
    blockedPatterns: ['revenue', 'profit margin', 'quarterly earnings', 'acquisition'],
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2026-01-10'),
    enforcementLevel: 'block',
  },
  {
    id: '3',
    name: 'Source Code Policy',
    description: 'Manages sharing of proprietary source code with AI coding assistants',
    status: 'active',
    dataClassifications: ['internal', 'confidential'],
    allowedTools: ['GitHub Copilot'],
    blockedPatterns: ['api_key', 'secret', 'password', 'private key'],
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2026-01-20'),
    enforcementLevel: 'warn',
  },
  {
    id: '4',
    name: 'Customer Data Policy',
    description: 'Protects customer information from unauthorized AI processing',
    status: 'active',
    dataClassifications: ['confidential', 'restricted'],
    allowedTools: [],
    blockedPatterns: ['customer list', 'client data', 'contact info', 'purchase history'],
    createdAt: new Date('2025-07-10'),
    updatedAt: new Date('2026-01-25'),
    enforcementLevel: 'block',
  },
  {
    id: '5',
    name: 'Healthcare Data Policy',
    description: 'HIPAA-compliant policy for healthcare information',
    status: 'active',
    dataClassifications: ['restricted'],
    allowedTools: [],
    blockedPatterns: ['patient', 'diagnosis', 'medical record', 'prescription', 'PHI'],
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2026-01-28'),
    enforcementLevel: 'block',
  },
];

// Data Assets
export const dataAssets: DataAsset[] = [
  {
    id: '1',
    name: 'Customer Database',
    type: 'Database',
    classification: 'restricted',
    owner: 'Data Team',
    department: 'Engineering',
    lastAccessed: new Date('2026-01-31T10:00:00'),
    accessCount: 1523,
    riskScore: 85,
  },
  {
    id: '2',
    name: 'Employee Records',
    type: 'Database',
    classification: 'confidential',
    owner: 'HR Team',
    department: 'HR',
    lastAccessed: new Date('2026-01-31T09:30:00'),
    accessCount: 234,
    riskScore: 72,
  },
  {
    id: '3',
    name: 'Financial Reports',
    type: 'Documents',
    classification: 'confidential',
    owner: 'Finance Team',
    department: 'Finance',
    lastAccessed: new Date('2026-01-31T08:45:00'),
    accessCount: 456,
    riskScore: 68,
  },
  {
    id: '4',
    name: 'Product Roadmap',
    type: 'Documents',
    classification: 'internal',
    owner: 'Product Team',
    department: 'Product',
    lastAccessed: new Date('2026-01-30T16:20:00'),
    accessCount: 789,
    riskScore: 45,
  },
  {
    id: '5',
    name: 'Marketing Materials',
    type: 'Documents',
    classification: 'public',
    owner: 'Marketing Team',
    department: 'Marketing',
    lastAccessed: new Date('2026-01-31T11:00:00'),
    accessCount: 2341,
    riskScore: 12,
  },
];

// AI Usage Events
export const aiUsageEvents: AIUsageEvent[] = [
  {
    id: '1',
    userId: '4',
    userName: 'James Liu',
    tool: 'ChatGPT',
    action: 'Text Generation',
    dataClassification: 'restricted',
    timestamp: new Date('2026-01-31T08:20:00'),
    blocked: true,
    riskLevel: 'critical',
    prompt: 'Summarize our Q4 earnings before the public announcement...',
    policyViolations: ['Financial Data Policy'],
  },
  {
    id: '2',
    userId: '2',
    userName: 'Michael Torres',
    tool: 'ChatGPT',
    action: 'Text Generation',
    dataClassification: 'confidential',
    timestamp: new Date('2026-01-31T09:15:00'),
    blocked: true,
    riskLevel: 'high',
    prompt: 'Help me draft an email with customer contact information...',
    policyViolations: ['Customer Data Policy', 'PII Protection Policy'],
  },
  {
    id: '3',
    userId: '1',
    userName: 'Sarah Chen',
    tool: 'GitHub Copilot',
    action: 'Code Completion',
    dataClassification: 'internal',
    timestamp: new Date('2026-01-31T10:30:00'),
    blocked: false,
    riskLevel: 'low',
    policyViolations: [],
  },
  {
    id: '4',
    userId: '3',
    userName: 'Emily Watson',
    tool: 'Claude',
    action: 'Document Analysis',
    dataClassification: 'internal',
    timestamp: new Date('2026-01-31T11:45:00'),
    blocked: false,
    riskLevel: 'low',
    policyViolations: [],
  },
  {
    id: '5',
    userId: '5',
    userName: 'Amanda Brooks',
    tool: 'ChatGPT',
    action: 'Text Generation',
    dataClassification: 'confidential',
    timestamp: new Date('2026-01-31T10:00:00'),
    blocked: true,
    riskLevel: 'high',
    prompt: 'Generate a report on employee performance reviews...',
    policyViolations: ['PII Protection Policy'],
  },
];

// Alerts
export const alerts: Alert[] = [
  {
    id: '1',
    type: 'Policy Violation',
    severity: 'critical',
    message: 'Attempted to share restricted financial data with ChatGPT',
    source: 'Financial Data Policy',
    timestamp: new Date('2026-01-31T08:20:00'),
    resolved: false,
    userId: '4',
    policyId: '2',
  },
  {
    id: '2',
    type: 'Policy Violation',
    severity: 'error',
    message: 'Customer PII detected in AI prompt',
    source: 'PII Protection Policy',
    timestamp: new Date('2026-01-31T09:15:00'),
    resolved: false,
    userId: '2',
    policyId: '1',
  },
  {
    id: '3',
    type: 'Unusual Activity',
    severity: 'warning',
    message: 'High volume of AI requests from single user',
    source: 'Anomaly Detection',
    timestamp: new Date('2026-01-31T07:30:00'),
    resolved: true,
    userId: '1',
  },
  {
    id: '4',
    type: 'New Tool Detected',
    severity: 'info',
    message: 'New AI tool "Perplexity" detected in network traffic',
    source: 'Network Monitor',
    timestamp: new Date('2026-01-31T06:45:00'),
    resolved: false,
  },
  {
    id: '5',
    type: 'Policy Violation',
    severity: 'error',
    message: 'Employee data shared with unauthorized AI tool',
    source: 'PII Protection Policy',
    timestamp: new Date('2026-01-31T10:00:00'),
    resolved: false,
    userId: '5',
    policyId: '1',
  },
];

// Compliance Frameworks
export const complianceFrameworks: ComplianceFramework[] = [
  {
    id: '1',
    name: 'GDPR',
    description: 'General Data Protection Regulation',
    overallScore: 96,
    requirements: [
      {
        id: '1-1',
        name: 'Data Minimization',
        description: 'Ensure only necessary data is processed',
        status: 'compliant',
        evidence: ['Policy 1', 'Audit Log 234'],
        lastAssessed: new Date('2026-01-15'),
      },
      {
        id: '1-2',
        name: 'Consent Management',
        description: 'Proper consent obtained for data processing',
        status: 'compliant',
        evidence: ['Consent Records'],
        lastAssessed: new Date('2026-01-15'),
      },
      {
        id: '1-3',
        name: 'Right to Erasure',
        description: 'Ability to delete personal data on request',
        status: 'compliant',
        evidence: ['Deletion Workflow'],
        lastAssessed: new Date('2026-01-15'),
      },
    ],
  },
  {
    id: '2',
    name: 'HIPAA',
    description: 'Health Insurance Portability and Accountability Act',
    overallScore: 92,
    requirements: [
      {
        id: '2-1',
        name: 'PHI Protection',
        description: 'Protected Health Information security',
        status: 'compliant',
        evidence: ['Healthcare Policy', 'Encryption Config'],
        lastAssessed: new Date('2026-01-20'),
      },
      {
        id: '2-2',
        name: 'Access Controls',
        description: 'Role-based access to health data',
        status: 'partial',
        evidence: ['RBAC Config'],
        lastAssessed: new Date('2026-01-20'),
      },
    ],
  },
  {
    id: '3',
    name: 'SOC 2',
    description: 'Service Organization Control 2',
    overallScore: 89,
    requirements: [
      {
        id: '3-1',
        name: 'Security',
        description: 'Protection against unauthorized access',
        status: 'compliant',
        evidence: ['Security Policies', 'Penetration Test'],
        lastAssessed: new Date('2026-01-10'),
      },
      {
        id: '3-2',
        name: 'Availability',
        description: 'System availability and reliability',
        status: 'compliant',
        evidence: ['Uptime Reports'],
        lastAssessed: new Date('2026-01-10'),
      },
      {
        id: '3-3',
        name: 'Confidentiality',
        description: 'Protection of confidential information',
        status: 'partial',
        evidence: ['Encryption Config'],
        lastAssessed: new Date('2026-01-10'),
      },
    ],
  },
  {
    id: '4',
    name: 'EU AI Act',
    description: 'European Union Artificial Intelligence Act',
    overallScore: 85,
    requirements: [
      {
        id: '4-1',
        name: 'Risk Assessment',
        description: 'AI system risk categorization',
        status: 'compliant',
        evidence: ['Risk Assessment Doc'],
        lastAssessed: new Date('2026-01-25'),
      },
      {
        id: '4-2',
        name: 'Transparency',
        description: 'Clear disclosure of AI usage',
        status: 'partial',
        evidence: ['AI Disclosure Policy'],
        lastAssessed: new Date('2026-01-25'),
      },
      {
        id: '4-3',
        name: 'Human Oversight',
        description: 'Human review of AI decisions',
        status: 'partial',
        evidence: ['Review Process'],
        lastAssessed: new Date('2026-01-25'),
      },
    ],
  },
];

// Time Series Data for Charts
export const requestsOverTime: TimeSeriesData[] = [
  { date: '12h ago', value: 1850 },
  { date: '11h ago', value: 2100 },
  { date: '10h ago', value: 2400 },
  { date: '9h ago', value: 2200 },
  { date: '8h ago', value: 1900 },
  { date: '7h ago', value: 1700 },
  { date: '6h ago', value: 1500 },
  { date: '5h ago', value: 1800 },
  { date: '4h ago', value: 2300 },
  { date: '3h ago', value: 2600 },
  { date: '2h ago', value: 2400 },
  { date: '1h ago', value: 2100 },
  { date: 'Now', value: 1950 },
];

export const blockedByCategory: TimeSeriesData[] = [
  { date: 'PII', value: 523, category: 'blocked' },
  { date: 'Financial', value: 312, category: 'blocked' },
  { date: 'Healthcare', value: 198, category: 'blocked' },
  { date: 'Source Code', value: 145, category: 'blocked' },
  { date: 'Customer', value: 65, category: 'blocked' },
];

export const usageByDepartment: TimeSeriesData[] = [
  { date: 'Engineering', value: 45000 },
  { date: 'Sales', value: 32000 },
  { date: 'Marketing', value: 28000 },
  { date: 'Finance', value: 15000 },
  { date: 'HR', value: 12000 },
  { date: 'Legal', value: 8000 },
];

export const riskTrend: TimeSeriesData[] = [
  { date: 'Jan 1', value: 35 },
  { date: 'Jan 5', value: 32 },
  { date: 'Jan 10', value: 28 },
  { date: 'Jan 15', value: 30 },
  { date: 'Jan 20', value: 25 },
  { date: 'Jan 25', value: 22 },
  { date: 'Jan 31', value: 23 },
];

// AI Tools
export const aiTools: AITool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    vendor: 'OpenAI',
    category: 'General Purpose',
    riskLevel: 'medium',
    approved: true,
    usageCount: 125000,
    lastUsed: new Date('2026-01-31T11:50:00'),
  },
  {
    id: '2',
    name: 'GitHub Copilot',
    vendor: 'Microsoft',
    category: 'Code Assistant',
    riskLevel: 'low',
    approved: true,
    usageCount: 89000,
    lastUsed: new Date('2026-01-31T11:45:00'),
  },
  {
    id: '3',
    name: 'Claude',
    vendor: 'Anthropic',
    category: 'General Purpose',
    riskLevel: 'low',
    approved: true,
    usageCount: 45000,
    lastUsed: new Date('2026-01-31T11:30:00'),
  },
  {
    id: '4',
    name: 'Jasper',
    vendor: 'Jasper AI',
    category: 'Marketing',
    riskLevel: 'medium',
    approved: true,
    usageCount: 23000,
    lastUsed: new Date('2026-01-31T10:00:00'),
  },
  {
    id: '5',
    name: 'Perplexity',
    vendor: 'Perplexity AI',
    category: 'Research',
    riskLevel: 'medium',
    approved: false,
    usageCount: 1200,
    lastUsed: new Date('2026-01-31T06:45:00'),
  },
  {
    id: '6',
    name: 'Midjourney',
    vendor: 'Midjourney',
    category: 'Image Generation',
    riskLevel: 'high',
    approved: false,
    usageCount: 3400,
    lastUsed: new Date('2026-01-30T15:20:00'),
  },
];
